spring.application.name=ecommerce


#spring.security.user.name=zaid
#spring.security.user.password=zaid
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceDB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#jwt.secret=your-256-bit-secret-key-your-256-bit-secret-key
#jwt.expiration=108000000   # 30 hours in milliseconds

#Redis Configuration
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

#Cloud Redis
